### ISSUE TITLE
JumpServer堡垒机

### ISSUE THREAD

**Issue by 0xfnzero** [TNK-Studio/gortal#13]
有计划实现JumpServer堡垒机的功能吗，那个真的好用，就是python开发的安装太麻烦，Go语言开发的安装简单

**Comment by elfgzp** [comment]
当初我就是在用想在自己的服务器装个 `JumpServer堡垒机` 无奈他的配置要求太高，太吃资源了。其实你可以用 docker 来装它，这样可以省去安装 python 的过程。

这个项目我是想给个人小组织使用，可能并不能达到他那种 4A 的专业运维审计的级别。不过会不断完善基础功能，将最需要的功能实现。

当初做这个项目的理念也是希望他轻量，可以满足跟人小组织，基友之间共享云计算资源。
