### ISSUE TITLE
cant docker pull elfgzp/gortal:latest

### ISSUE THREAD

**Issue by zzninjia** [TNK-Studio/gortal#14]
文档写的 docker pull elfgzp/gortal:latest，无法拉取镜像，因为在 docker hub 中，并不存在 latest 的 tag。可以把 最新的 elfgzp/gortal:1.2.4  tag为  elfgzp/gortal:latest 再传到docker hub 啦

**Comment by elfgzp** [comment]
非常感谢提醒 🙏 是我忘记给 docker hub 加上 latest 的镜像规则了
现在加上了
