### ISSUE TITLE
删除用户bug

### ISSUE THREAD

**Issue by Geometry6151** [TNK-Studio/gortal#27]
当删除一个用户的时候，会爆一个配置中不存在userx的错误

![image](https://user-images.githubusercontent.com/40165502/97661249-cf54b980-1aae-11eb-81c3-708ef71748c9.png)

把 core/pui/menu.go的第85行改成       userKey := fmt.Sprintf("users%d", index+1)      就行了

**Comment by elfgzp** [comment]
@09577 你可以直接提个 pull request 给我 这样你也是贡献者了 👍

**Comment by elfgzp** [comment]
@09577 v1.3.0 已发布
