### ISSUE TITLE
启动时，登录不了

### ISSUE THREAD

**Issue by ZScai** [TNK-Studio/gortal#32]
![image](https://user-images.githubusercontent.com/86775125/164411083-4758d6e0-c147-4bf9-a947-deae524419c2.png)
![image](https://user-images.githubusercontent.com/86775125/164411194-d3d74cc8-0947-41fd-bd7f-ae75fca82bb0.png)

**Comment by testerzhang** [comment]
第一次输入默认密码newuser，进入新用户创建流程，最后会自动生成这个文件
